packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - simple-icons@16.32.0
overrides:
  react: 19.3.0
peerDependencyRules:
  allowAny:
    - react
    - react-dom
